from _typeshed import Incomplete

def formatwarning(message, category, filename, lineno, line: Incomplete | None = ...): ...

class PymelBaseWarning(Warning): ...
class ExecutionWarning(UserWarning, PymelBaseWarning): ...
class PymelBaseDeprecationWarning(PymelBaseWarning): ...
class PymelFutureWarning(FutureWarning, PymelBaseDeprecationWarning): ...
class MayaDeprecationWarning(DeprecationWarning, PymelBaseDeprecationWarning): ...

def warn(*args, **kwargs): ...
def deprecated(funcOrMessage: Incomplete | None = ..., className: Incomplete | None = ..., baseMessage: str = ..., warningType=...): ...
def maya_deprecated(funcOrMessage: Incomplete | None = ..., className: Incomplete | None = ..., baseMessage: str = ..., warningType=...): ...
