from .path import path as path
from _typeshed import Incomplete
from collections.abc import Generator
from re import escape as escape
from typing import Any

TYPE_CHECKING = False

def inMaya(): ...
def capitalize(s: Any) -> str: ...
def uncapitalize(s: Any, preserveAcronymns: Any = ...) -> str: ...
def unescape(s: Any) -> str: ...
def cacheProperty(getter, attr_name, fdel: Incomplete | None = ..., doc: Incomplete | None = ...): ...
def timer(command: str = ..., number: int = ..., setup: str = ...): ...
def interpreterBits() -> int: ...
def toZip(directory, zipFile): ...
def subpackages(packagemod) -> Generator[Incomplete, None, None]: ...
