from .path import path as path
from _typeshed import Incomplete
from collections.abc import Generator
from re import escape as escape

TYPE_CHECKING: bool

def inMaya() -> bool: ...
def capitalize(s: str) -> str: ...
def uncapitalize(s: str, preserveAcronymns: bol = ...) -> str: ...
def unescape(s: str) -> str: ...
def cacheProperty(getter, attr_name, fdel: Incomplete | None = ..., doc: Incomplete | None = ...): ...
def timer(command: str = ..., number: int = ..., setup: str = ...) -> float: ...
def interpreterBits() -> int: ...
def toZip(directory, zipFile): ...
def subpackages(packagemod) -> Generator[Incomplete, None, None]: ...
