from _typeshed import Incomplete

def decorated(origFunc, newFunc, decoration: Incomplete | None = ...) -> None: ...
def decorator(func): ...
def format_signature(args=..., varargs: Incomplete | None = ..., varkw: Incomplete | None = ..., defaults: Incomplete | None = ...): ...
def interface_wrapper(doer, args=..., varargs: Incomplete | None = ..., varkw: Incomplete | None = ..., defaults: Incomplete | None = ...): ...
