from . import utilitytypes as utilitytypes
from _typeshed import Incomplete
from past.builtins import cmp as cmp
from typing import Any

__author_name__: str
__author_email__: str
__date__: str
__url__: str

class EnumException(Exception):
    def __init__(self) -> None: ...

class EnumEmptyError(AssertionError, EnumException): ...

class EnumBadKeyError(TypeError, EnumException):
    key: Incomplete
    def __init__(self, key) -> None: ...

class EnumImmutableError(TypeError, EnumException):
    args: Incomplete
    def __init__(self, *args) -> None: ...

class EnumBadDefaultKeyError(ValueError, EnumException):
    val: Incomplete
    key: Incomplete
    def __init__(self, val, key) -> None: ...

class EnumValue:
    def __init__(self, enumtype, index, key, doc: Incomplete | None = ...) -> None: ...
    enumtype: Incomplete
    key: Incomplete
    def __int__(self): ...
    index: Incomplete
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __lt__(self, other): ...
    def __ge__(self, other): ...
    def __le__(self, other): ...

class Enum:
    def __init__(self, name: str, keys: Union[Dict[str, int], Iterable[str], Iterable[Tuple[str, int]]], **kwargs: Any) -> None: ...
    @property
    def name(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __ne__(self, other): ...
    def __setattr__(self, name, value) -> None: ...
    def __delattr__(self, name) -> None: ...
    def __len__(self): ...
    def __getitem__(self, index): ...
    def __setitem__(self, index, value) -> None: ...
    def __delitem__(self, index) -> None: ...
    def __iter__(self): ...
    def __contains__(self, value): ...
    def getIndex(self, key): ...
    def getKey(self, index): ...
    def values(self): ...
    def itervalues(self): ...
    def keys(self): ...
EnumType = Enum

class EnumDict(utilitytypes.EquivalencePairs):
    def __init__(self, keys, **kwargs) -> None: ...
    def value(self, key: Union[str, int]) -> int: ...
    def key(self, index: int) -> str: ...
    def values(self): ...
    def keys(self): ...
