from typing import *

def conjugate(x): ...
def real(x): ...
def imag(x): ...
def round(value, ndigits: int = ...): ...
def gamma(c: float, g: float) -> float: ...
def blend(a: float, b: float, weight: float = ...) -> float: ...
def smoothmap(min: float, max: float, x: SupportsFloat) -> float: ...
def smoothstep(min: float, max: float, x: float) -> float: ...
def linmap(min: float, max: float, x: SupportsFloat) -> float: ...
def linstep(min: float, max: float, x: float) -> float: ...
def clamp(x: float = ..., min: float = ..., max: float = ...) -> float: ...
def setRange(x: float = ..., oldmin: float = ..., oldmax: float = ..., newmin: float = ..., newmax: float = ...) -> float: ...
def hermiteInterp(x: float = ..., y0: float = ..., y1: float = ..., s0: float = ..., s1: float = ...) -> float: ...
def hermite(x: float = ..., v0: float = ..., v1: float = ..., s0: float = ..., s1: float = ...) -> float: ...
